#!/bin/sh 
#set -x

# Simple script to generate testcases using a well known implementation (openssl).
# This script is the source of the values used when comparing the result of crypto.

KEY128="01234567890123456789012345678901" # 128 is not being used right now so key is not important
KEY256="732FE849725D6FB098B5CB8BA0D4812AC44F83A63F3A23CA41C0B2B941F84488" # Key generated by McEliece given the seed used in exampleTransfer.sh
IV="10987654321098765432109876543210" # Can be anything but needs to be equal to the one used in exampleTransfer.sh in order to give the same results

echo -n "Test string, contains multiple characters in order to test the block stream properly" > in.txt

echo ""
openssl sha256 in.txt

openssl aes-128-ecb -in in.txt -K $KEY128 -e > out_128_ecb.txt
echo ""
echo "ECB 128"
echo ""
xxd -p out_128_ecb.txt
openssl aes-128-ecb -in out_128_ecb.txt -K $KEY128 -d > out_128_ecb_decrypt.txt

openssl aes-256-ecb -in in.txt -K $KEY256 -e > out_256_ecb.txt
echo ""
echo "ECB 256"
echo ""
xxd -p out_256_ecb.txt
openssl aes-256-ecb -in out_256_ecb.txt -K $KEY256 -d > out_256_ecb_decrypt.txt

openssl aes-128-cbc -in in.txt -K $KEY128 -iv $IV -e > out_128_cbc.txt
echo ""
echo "CBC 128"
echo ""
xxd -p out_128_cbc.txt
openssl aes-128-cbc -in out_128_cbc.txt -K $KEY128 -iv $IV -d > out_128_cbc_decrypt.txt

openssl aes-256-cbc -in in.txt -K $KEY256 -iv $IV -e > out_256_cbc.txt
echo ""
echo "CBC 256"
echo ""
xxd -p out_256_cbc.txt
openssl aes-256-cbc -in out_256_cbc.txt -K $KEY256 -iv $IV -d > out_256_cbc_decrypt.txt

echo ""
echo "Just to visually check if everything is correct:"
echo ""

xxd -p -l 25 in.txt
xxd -p -l 25 out_128_ecb_decrypt.txt
xxd -p -l 25 out_256_ecb_decrypt.txt
xxd -p -l 25 out_128_cbc_decrypt.txt
xxd -p -l 25 out_256_cbc_decrypt.txt

echo ""

xxd -p -l 25 -seek 25 in.txt
xxd -p -l 25 -seek 25 out_128_ecb_decrypt.txt
xxd -p -l 25 -seek 25 out_256_ecb_decrypt.txt
xxd -p -l 25 -seek 25 out_128_cbc_decrypt.txt
xxd -p -l 25 -seek 25 out_256_cbc_decrypt.txt

echo ""

xxd -p -l 25 -seek 50 in.txt
xxd -p -l 25 -seek 50 out_128_ecb_decrypt.txt
xxd -p -l 25 -seek 50 out_256_ecb_decrypt.txt
xxd -p -l 25 -seek 50 out_128_cbc_decrypt.txt
xxd -p -l 25 -seek 50 out_256_cbc_decrypt.txt

rm *.txt
